### ISSUE TITLE
Support custom scripts that rendres images (mermaid)

### ISSUE THREAD

**Issue by cblomart** [yzane/vscode-markdown-pdf#51] opened 2018-01-20 20:15 UTC
Hello,

Is it possible to support custom scripting that renders images.

I more specificaly do use mermaid in my markdowns that are nicely renderd in vscode by its extention:
https://github.com/vstirbu/vscode-mermaid-preview

I did open an issue with them also:
https://github.com/vstirbu/vscode-mermaid-preview/issues/47

Thanks

**Comment by cblomart** [comment] 2018-01-24 18:37
See reaction of vstribu in opened issue.

**Comment by yzane** [comment] 2018-04-22 05:42
Closing as dupe of #30

**Closed by yzane** 2018-04-22 05:42 UTC
