### ISSUE TITLE
Multiple Exports Formats?

### ISSUE THREAD

**Issue by wrrq** [yzane/vscode-markdown-pdf#34] opened 2017-09-19 09:38 UTC
Hey,

I tried to export a markdown file to pdf and html but it failed with

    "markdown-pdf.type": "pdf, html"

Is it somehow possible to achieve this without switching the settings all the time?

Best regards

**Comment by yzane** [comment] 2017-10-05 13:27
Duplicate of #20

**Comment by rizickus** [comment] 2017-11-16 13:52
Is there any progress regarding this feature?

**Comment by yzane** [comment] 2018-04-15 14:05
Closing as dupe of #20

**Closed by yzane** 2018-04-15 14:05 UTC
Labels: duplicate
