### ISSUE TITLE
Mermaid Not Rendering

### ISSUE THREAD

**Issue by mgoppert** [yzane/vscode-markdown-pdf#313] opened 2023-02-24 15:53 UTC
We are using the latest version of VSCode (v1.75.1) along with Markdown PDF (v1.4.4). It appears all mermaid, no matter how simple, is no longer rendering as an image. The code shows instead. Is anyone else experiencing this?

Code
```code
  ``` mermaid
  graph LR
      ID["App or Step Name"]
```

Renders
![image](https://user-images.githubusercontent.com/87670311/221225553-c409256f-9cf6-4393-a23a-f40594d39e9a.png)

**Comment by b2m** [comment] 2023-02-24 16:52
Duplicate of #312 .

The temporary workaround is to set the `markdown-pdf.mermaidServer` setting with `https://unpkg.com/mermaid@9.4.0/dist/mermaid.min.js` or a newer version.

**Closed as completed** 2023-04-13 13:29 UTC

**Comment by gvarela1981** [comment] 2025-01-10 15:49
Version 9.4.0 is outdated and does not support some of mermaid's diagrams. I've tried using a newer one but doesn't seem to work, it may be broken in npm
I've tried versions available in 3 different CDN
https://cdnjs.com/libraries/mermaid/11.4.0
https://unpkg.com/browse/mermaid@11.4.0/
https://cdn.jsdelivr.net/npm/mermaid@11.4.1/+esm
