### ISSUE TITLE
Link To Headers

### ISSUE THREAD

**Issue by prantikv** [yzane/vscode-markdown-pdf#6] opened 2016-12-04 16:51 UTC
I would like to see the feature where it would be possible to link to headers of the same file. This can be used to create table of contents

See here http://stackoverflow.com/questions/3292903/in-markdown-what-is-the-best-way-to-link-to-a-fragment-of-a-page-i-e-some-id

**Comment by shuffle2** [comment] 2017-02-19 10:26
+1 ... Currently it will unhelpfully create a link to
```
file:///<file directory>/<markdown link path>
```
which doesn't do anything useful :p

**Comment by shuffle2** [comment] 2017-02-19 12:18
part of the problem seems to be that the generated header tags do not have `id`s. There is a markdown-it module to add them: https://www.npmjs.com/package/markdown-it-named-headers

**Comment by PaulBernhardt** [comment] 2017-06-26 19:51
I would love to have a way to make this work with [AlanWalk/Markdown-TOC](https://github.com/AlanWalk/Markdown-TOC) to get a hyperlinked table of contents that works in a PDF.

**Comment by prantikv** [comment] 2017-11-12 04:35
Any update on this. It has been a year.

**Comment by yzane** [comment] 2018-04-15 13:17
Closing as dupe of #31

**Closed by yzane** 2018-04-15 13:17 UTC
Labels: duplicate
