### ISSUE TITLE
markdown pdf installing puppeteer

### ISSUE THREAD

**Issue by mmjbds999** [yzane/vscode-markdown-pdf#78] opened 2018-04-25 08:04 UTC

**Comment by mmjbds999** [comment] 2018-04-25 08:05
in windows os

**Comment by douglaswaugh** [comment] 2018-04-25 10:00
I also received an error with the markdown pdf plug-in this morning with respect to puppeteer:

Command failed: npm rebuild puppeteer C:\Users\[redacted username]\.vscode\extensions\yzane.markdown-pdf-1.0.1\node_modules\puppeteer\install.js:80 let progressBar = null; ^^^ SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode at exports.runInThisContext (vm.js:53:16) at Module._compile (module.js:373:25) at Object.Module._extensions..js (module.js:416:10) at Module.load (module.js:343:32) at Function.Module._load (module.js:300:12) at Function.Module.runMain (module.js:441:10) at startup (node.js:139:18) at node.js:968:3 npm ERR! Windows_NT 10.0.16299 npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "puppeteer" npm ERR! node v4.4.5 npm ERR! npm v2.15.5 npm ERR! code ELIFECYCLE npm ERR! puppeteer@1.3.0 install: `node install.js` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the puppeteer@1.3.0 install script...

Windows 10 Pro v1709
VS Code v1.22.2
Markdown Pdf v1.0.1

Thanks

![image](https://user-images.githubusercontent.com/1898630/39239116-e29fbe10-4877-11e8-9351-3f34860fa881.png)
![image](https://user-images.githubusercontent.com/1898630/39239078-cf3994e0-4877-11e8-971a-5315b44cf96d.png)

**Comment by yzane** [comment] 2018-04-25 15:44
Closing as dupe of #77

**Closed by yzane** 2018-04-25 15:44 UTC
